[server]
# server addr
addr="127.0.0.1:7556"
# used to verify whether the service_name
service-name="file-store-service"
# used to verify whether the verify_key
verify_key=""
# the timeout period for the client to request the server
request_out_time_ms=5000

# used to configure TLS communication encryption (optional).
# if not provided, TLS will not be used for communication encryption
[tls]
# ca file path (optional)
# if not provided, the client’s certificate will not be verified.
ca = "./tls/ca.crt"

# cert file path
cert = "./tls/server-crt.pem"

# key file path
key = "./tls/server-key.pem"